[Log]
level = "info"
prefix = ""
root_path = "/var/logs/embystream"

[General]
memory_mode = "middle"
stream_mode = "frontend"
backend_type = "disk"
encipher_key = "Q4eCbawEp3sCvDvx"
encipher_iv = "a3cH2abhxnu9hGo5"

[Emby]
url = "http://127.0.0.1"
port = "8096"
token = "nmbp7mpixze8ghdfgki6yrijkeq5zuao"

[UserAgent]
mode = "deny"
allow_ua = []
deny_ua = ["curl", "wget", "python", "fimily", "infuse-library"]

[Http2]
ssl_cert_file = ""
ssl_key_file = ""

[Fallback]
video_missing_path = "/mnt/anime/fallback/video_missing.mp4"

[Frontend]
listen_port = 60001
check_file_existence = true

[[Frontend.PathRewrite]]
enable = false
pattern = "^(/.*)$"
replacement = "https://my-cdn.com$1"

[[Frontend.PathRewrite]]
enable = false
pattern = "^/media(/.*)$"
replacement = "$1"

[[Frontend.PathRewrite]]
enable = false
pattern = "^/stream(/.*)$"
replacement = "/proxy$1"

[Frontend.AntiReverseProxy]
enable = false
host = ""
