[package]
name = "embystream"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
rust-version = "1.85"
authors = ["Open-PiliPili <openpilipili@gmail.com>"]
description = "Another Emby streaming application (frontend/backend separation) written in Rust."

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
cbc = "0.1.2"
cipher = "0.4.4"
dashmap = "6.1.0"
generic-array = "1.2.0"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
time = { version = "0.3.39", features = ["macros", "local-offset"] }
toml = "0.8.22"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = [
    "std",
    "fmt",
    "env-filter",
    "tracing-log",
    "time",
    "local-time",
    "json"
] }
uuid = { version = "1.16.0", features = ["v4"] }