name: Manual Release Build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
            target_name: amd64
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest-arm64
            target_name: aarch64

    runs-on: ${{ matrix.os }}
    name: Build Release for ${{ matrix.target_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install build dependencies
        run: sudo apt-get update -y && sudo apt-get install -y musl-tools

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Verify build output
        run: ls -lh target/${{ matrix.target }}/release/embystream
